<?php
/**
 * Jamroom 5 YouTube Support module
 *
 * copyright 2003 - 2015
 * by paul
 *
 * This Jamroom file is LICENSED SOFTWARE, and cannot be redistributed.
 *
 * This Source Code is subject to the terms of the Jamroom Network
 * Commercial License -  please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * paul
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// Profile Menu Entry Name
$lang['menu'] = 'youtube';

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'Search String';
$lang[2]  = 'Create New Embedded YouTube Video';
$lang[3]  = 'Create';
$lang[4]  = 'YouTube ID or URL';
$lang[5]  = 'Enter the ID or URL for the youtube video - the YouTube ID is the 11 character ID found in the youtube URL. Alternatively you can just enter the full URL and the ID will be extracted from it.';
$lang[6]  = 'YouTube video created';
$lang[7]  = 'Unable to retrieve video data from YouTube';
$lang[8]  = 'Unable to extract the YouTube ID from the URL - please try again or enter the ID';
$lang[9]  = 'Unable to retrieve the any data for the given YouTube ID - please check the URL and try again';
$lang[10] = 'Invalid item ID';
$lang[11] = 'Update Embedded YouTube Video';
$lang[12] = 'Update';
$lang[13] = 'Title';
$lang[14] = 'Category';
$lang[15] = 'Update the title of this YouTube video';
$lang[16] = 'Update the category of this YouTube video';
$lang[17] = 'Description';
$lang[18] = 'Update the description of this YouTube video';
$lang[19] = 'Unable to retrieve video data from YouTube';
$lang[20] = 'Unable to extract YouTube ID';
$lang[21] = 'YouTube video updated';
$lang[22] = 'Search String';
$lang[23] = 'Search or Import Selected';
$lang[24] = 'Enter search text';
$lang[25] = 'Start Page';
$lang[26] = 'you have selected an invalid page number';
$lang[27] = 'Results per Page';
$lang[28] = 'you have selected an invalid page break';
$lang[29] = 'Player';
$lang[30] = 'Info';
$lang[31] = 'Description';
$lang[32] = 'Import';
$lang[33] = 'No Youtube videos found for';
$lang[34] = 'YouTube videos imported';
$lang[35] = 'Duration';
$lang[36] = 'Posted a new YouTube video';
$lang[37] = 'Order by';
$lang[38] = 'How do you want order the return results.';
$lang[39] = 'Select All';
$lang[40] = 'YouTube';
$lang[41] = 'youtube videos';
$lang[42] = 'insert youtube video';
$lang[43] = 'no youtube videos were found';
$lang[44] = 'TIP: Use the YouTube Search tool to import multiple YouTube videos at a time:';
$lang[45] = 'YouTube Search';
$lang[46] = 'Updated a YouTube Video';
$lang[47] = 'Unable to create new YouTube entry - please try again';
$lang[48] = 'This YouTube video has already been uploaded';
$lang[49] = 'Uploaded by';
$lang[50] = 'Created';
$lang[51] = 'Updated';
$lang[52] = 'Rating';
$lang[53] = 'Views';
$lang[54] = 'Posted new YouTube videos';
