<?php
/**
 * Jamroom 5 System Core module
 *
 * copyright 2003 - 2015
 * by The Jamroom Network
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0.  Please see the included "license.html" file.
 *
 * This module may include works that are not developed by
 * The Jamroom Network
 * and are used under license - any licenses are included and
 * can be found in the "contrib" directory within this module.
 *
 * Jamroom may use modules and skins that are licensed by third party
 * developers, and licensed under a different license  - please
 * reference the individual module or skin license that is included
 * with your installation.
 *
 * This software is provided "as is" and any express or implied
 * warranties, including, but not limited to, the implied warranties
 * of merchantability and fitness for a particular purpose are
 * disclaimed.  In no event shall the Jamroom Network be liable for
 * any direct, indirect, incidental, special, exemplary or
 * consequential damages (including but not limited to, procurement
 * of substitute goods or services; loss of use, data or profits;
 * or business interruption) however caused and on any theory of
 * liability, whether in contract, strict liability, or tort
 * (including negligence or otherwise) arising from the use of this
 * software, even if advised of the possibility of such damage.
 * Some jurisdictions may not allow disclaimers of implied warranties
 * and certain statements in the above disclaimer may not apply to
 * you as regards implied warranties; the other terms and conditions
 * remain enforceable notwithstanding. In some jurisdictions it is
 * not permitted to limit liability and therefore such limitations
 * may not apply to you.
 *
 * @copyright 2012 Talldude Networks, LLC.
 * @author Brian Johnson <brian [at] jamroom [dot] net>
 */

// make sure we are not being called directly
defined('APP_DIR') or exit();

// DO NOT EDIT THIS FILE. THIS FILE IS ONLY LOADED DURING INSTALLATION.
// ANY CHANGES TO LANGUAGE STRINGS SHOULD BE DONE IN THE CONTROL PANEL!
$lang[1]  = 'save';
$lang[2]  = 'cancel';
$lang[3]  = 'options';
$lang[4]  = 'settings';
$lang[5]  = 'tools';
$lang[6]  = 'config';
$lang[7]  = 'enable';
$lang[8]  = 'search';
$lang[9]  = 'undo changes';
$lang[10] = 'January';
$lang[11] = 'February';
$lang[12] = 'March';
$lang[13] = 'April';
$lang[14] = 'May';
$lang[15] = 'June';
$lang[16] = 'July';
$lang[17] = 'August';
$lang[18] = 'September';
$lang[19] = 'October';
$lang[20] = 'November';
$lang[21] = 'December';
$lang[22] = 'notice';
$lang[23] = 'warning';
$lang[24] = 'error';
$lang[25] = 'success';
$lang[26] = '&lt;';
$lang[27] = '&gt;';
$lang[28] = 'close';
$lang[29] = 'reset';
$lang[30] = 'You have entered an invalid value for &quot;';
$lang[31] = '&quot; - value must be';
$lang[32] = 'date';
$lang[33] = 'log text';
$lang[34] = 'expand help';
$lang[35] = 'only site admins can log in while the site is in maintenance mode';
$lang[36] = 'create';
$lang[37] = 'update';
$lang[38] = 'delete';
$lang[39] = 'select';
$lang[40] = 'are you sure you want to delete this item?';
$lang[41] = 'You do not have the proper privileges to perform that action!';
$lang[42] = 'The file(s) you attempted to upload are larger then allowed - please select smaller files for upload.';
$lang[43] = 'upload a file';
$lang[44] = 'upload failed';
$lang[45] = 'upload files';
$lang[46] = 'upload another';
$lang[47] = 'select existing:';
$lang[48] = 'new value:';
$lang[49] = 'max upload:';
$lang[50] = 'Create New Entry';
$lang[51] = 'seconds ago';
$lang[52] = 'a second ago';
$lang[53] = 'minutes ago';
$lang[54] = 'a minute ago';
$lang[55] = 'hours ago';
$lang[56] = 'an hour ago';
$lang[57] = 'days ago';
$lang[58] = 'yesterday';
$lang[59] = 'weeks ago';
$lang[60] = 'one week ago';
$lang[61] = 'months ago';
$lang[62] = 'one month ago';
$lang[63] = 'years ago';
$lang[64] = 'last year';
$lang[65] = 'There is already an entry using the same ';
$lang[66] = ' - please enter a unique value';
$lang[67] = 'Your entry contains the following text which is not allowed: ';
$lang[68] = 'Allowed File Types:';
$lang[69] = '(per file)';
$lang[70] = 'You have created the maximum number of items of this type allowed by your Quota plan';
$lang[71] = 'This item is currently pending approval by an admin, and will be visible on your profile once approved.';
$lang[72] = 'save changes';
$lang[73] = 'working...';
$lang[74] = 'file name';
$lang[75] = 'file size';
$lang[76] = 'file date';
$lang[77] = 'Your item has been approved and is now on your profile!';
$lang[78] = 'Your item has been rejected for the following reasons:';
$lang[79] = 'Once you fix these issues it can be viewable on your profile.';
$lang[80] = 'Your item has been rejected - please resubmit';
$lang[81] = 'You forgot to select a file to upload';
$lang[82] = 'item(s) max';
$lang[83] = 'set item order';
$lang[84] = 'Not Found';
